### ISSUE TITLE
Background Problem

### ISSUE THREAD

**Issue by anna-pokhilenko** [anna-pokhilenko/kraken-good-accessibility#1]
@JessJodoin 
Hello)

**Comment by JessJodoin** [comment]
Okay! Try adding this background colour to your `<header>` instead

`background-color: #1e7c74;`

**Comment by anna-pokhilenko** [comment]
Still doesn't like it.((

@JessJodoin

**Comment by anna-pokhilenko** [comment]
I even tried #000 haha

**Comment by JessJodoin** [comment]
What does the markbot issue say again?

**Comment by anna-pokhilenko** [comment]
<img width="518" alt="Screen Shot 2020-09-29 at 10 40 41 PM" src="https://user-images.githubusercontent.com/55008926/94637148-d10b4180-02a4-11eb-9803-9c2c9ef73653.png">

**Comment by anna-pokhilenko** [comment]
damn, it's a footer

**Comment by JessJodoin** [comment]
Add that background-color to the footer too then

**Comment by anna-pokhilenko** [comment]
It worked, thank you!
You are amazing!

**Comment by JessJodoin** [comment]
Yay! Happy to help 😊

**Comment by JessJodoin** [comment]
Hey! Could close this issue?
